version: 1

before:
  hooks:
    - go mod tidy
    - pnpm install --prefix web
    - pnpm run release --prefix web

builds:
  - main: ./main.go
    binary: wekalist
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags: >-
      -s -w -X github.com/imrany/wekalist/internal/version.version={{ .Tag }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - server/router/frontend/dist/**

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  disable: true

release:
  draft: true
  replace_existing_draft: true
  make_latest: true
  mode: replace
  skip_upload: false

dockers:
  - dockerfile: scripts/Dockerfile
    image_templates:
      - ghcr.io/imrany/wekalist:{{ .Tag }}
      - ghcr.io/imrany/wekalist:latest
    build_flag_templates:
      - --platform=linux/amd64,linux/arm64
    skip_push: false
    use: buildx
