// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: store/attachment.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";
import { StorageS3Config } from "./workspace_setting";

export const protobufPackage = "wekalist.store";

export enum AttachmentStorageType {
  ATTACHMENT_STORAGE_TYPE_UNSPECIFIED = "ATTACHMENT_STORAGE_TYPE_UNSPECIFIED",
  /** LOCAL - Attachment is stored locally. AKA, local file system. */
  LOCAL = "LOCAL",
  /** S3 - Attachment is stored in S3. */
  S3 = "S3",
  /** EXTERNAL - Attachment is stored in an external storage. The reference is a URL. */
  EXTERNAL = "EXTERNAL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function attachmentStorageTypeFromJSON(object: any): AttachmentStorageType {
  switch (object) {
    case 0:
    case "ATTACHMENT_STORAGE_TYPE_UNSPECIFIED":
      return AttachmentStorageType.ATTACHMENT_STORAGE_TYPE_UNSPECIFIED;
    case 1:
    case "LOCAL":
      return AttachmentStorageType.LOCAL;
    case 2:
    case "S3":
      return AttachmentStorageType.S3;
    case 3:
    case "EXTERNAL":
      return AttachmentStorageType.EXTERNAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AttachmentStorageType.UNRECOGNIZED;
  }
}

export function attachmentStorageTypeToNumber(object: AttachmentStorageType): number {
  switch (object) {
    case AttachmentStorageType.ATTACHMENT_STORAGE_TYPE_UNSPECIFIED:
      return 0;
    case AttachmentStorageType.LOCAL:
      return 1;
    case AttachmentStorageType.S3:
      return 2;
    case AttachmentStorageType.EXTERNAL:
      return 3;
    case AttachmentStorageType.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface AttachmentPayload {
  s3Object?: AttachmentPayload_S3Object | undefined;
}

export interface AttachmentPayload_S3Object {
  s3Config?:
    | StorageS3Config
    | undefined;
  /** key is the S3 object key. */
  key: string;
  /**
   * last_presigned_time is the last time the object was presigned.
   * This is used to determine if the presigned URL is still valid.
   */
  lastPresignedTime?: Date | undefined;
}

function createBaseAttachmentPayload(): AttachmentPayload {
  return { s3Object: undefined };
}

export const AttachmentPayload: MessageFns<AttachmentPayload> = {
  encode(message: AttachmentPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.s3Object !== undefined) {
      AttachmentPayload_S3Object.encode(message.s3Object, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AttachmentPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAttachmentPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.s3Object = AttachmentPayload_S3Object.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AttachmentPayload>): AttachmentPayload {
    return AttachmentPayload.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AttachmentPayload>): AttachmentPayload {
    const message = createBaseAttachmentPayload();
    message.s3Object = (object.s3Object !== undefined && object.s3Object !== null)
      ? AttachmentPayload_S3Object.fromPartial(object.s3Object)
      : undefined;
    return message;
  },
};

function createBaseAttachmentPayload_S3Object(): AttachmentPayload_S3Object {
  return { s3Config: undefined, key: "", lastPresignedTime: undefined };
}

export const AttachmentPayload_S3Object: MessageFns<AttachmentPayload_S3Object> = {
  encode(message: AttachmentPayload_S3Object, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.s3Config !== undefined) {
      StorageS3Config.encode(message.s3Config, writer.uint32(10).fork()).join();
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.lastPresignedTime !== undefined) {
      Timestamp.encode(toTimestamp(message.lastPresignedTime), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AttachmentPayload_S3Object {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAttachmentPayload_S3Object();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.s3Config = StorageS3Config.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastPresignedTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AttachmentPayload_S3Object>): AttachmentPayload_S3Object {
    return AttachmentPayload_S3Object.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AttachmentPayload_S3Object>): AttachmentPayload_S3Object {
    const message = createBaseAttachmentPayload_S3Object();
    message.s3Config = (object.s3Config !== undefined && object.s3Config !== null)
      ? StorageS3Config.fromPartial(object.s3Config)
      : undefined;
    message.key = object.key ?? "";
    message.lastPresignedTime = object.lastPresignedTime ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
